if [ -e 'build' ]; then
    echo "Folder exists."
else
    mkdir build
fi

cd build
cmake -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_DEVICE_ARM64:BOOL="ON" -DBUILD_IOS_DEVICE_ARM64E:BOOL="ON" -DBUILD_IOS_DEVICE_ARMV7:BOOL="ON" -DBUILD_IOS_DEVICE_ARMV7S:BOOL="ON" -DBUILD_IOS_SIMULATOR:BOOL="ON" -DBUILD_IOS_SIMULATOR_X86_64:BOOL="ON" -DBUILD_IOS_SIMULATOR_I386:BOOL="ON" ../
make -j12
# cmake -GNinja -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_DEVICE_ARM64:BOOL="ON" -DBUILD_IOS_DEVICE_ARMV7:BOOL="ON" -DBUILD_IOS_DEVICE_ARMV7S:BOOL="ON" -DBUILD_IOS_SIMULATOR:BOOL="ON" -DBUILD_IOS_SIMULATOR_X86_64:BOOL="OFF" -DBUILD_IOS_SIMULATOR_I386:BOOL="OFF" ../
# cmake --build . --config Release
# cmake --build . --config Debug

