cmake -H. -Bbuild -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_DEVICE_ARM64:BOOL="ON" -DBUILD_IOS_DEVICE_ARM64E:BOOL="ON" -DBUILD_IOS_DEVICE_ARMV7:BOOL="ON" -DBUILD_IOS_DEVICE_ARMV7S:BOOL="ON" -DBUILD_IOS_SIMULATOR:BOOL="ON" -DBUILD_IOS_SIMULATOR_X86_64:BOOL="ON" -DBUILD_IOS_SIMULATOR_I386:BOOL="ON"
cd build
make -j12
