# Podfile -- alternative to the XcodeGen + local-XCFramework setup.
#
# Use this when you want to consume PCLMobile from CocoaPods Trunk instead
# of linking the local build under ../../../build/ios/xcframework/.
#
# Usage:
#   pod install --project-directory=.
#   open PCLMobileBasicSample.xcworkspace
#
# Switch back to the local XCFramework path by uncommenting the `:path =>`
# line and commenting out the version-pinned line.

platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'PCLMobileBasicSample' do
  pod 'PCLMobile', '~> 0.1'
  # pod 'PCLMobile', :path => '../../../iOSWrapper'

  target 'PCLMobileBasicSampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CLANG_MODULES_AUTOLINK'] = 'NO'
    end
  end
end
